### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by nechtas** [devtodev-analytics/android-sdk-2.0#1]
Hello. We made a Flutter package for iOS and Android. Everything was working well in debug (for iOS this is working in production already), but on the Android platform when we make the release build app started crashing on sdk intialization:

```
E/AndroidRuntime(14997): FATAL EXCEPTION: pool-70-thread-1
E/AndroidRuntime(14997): Process: xxx.xxx.xxx, PID: 14997
E/AndroidRuntime(14997): java.lang.Exception: Missing dependency com.devtodev:android-google or com.devtodev:android-huawei.
E/AndroidRuntime(14997): Possibly incorrect implementation of COPPA control.
E/AndroidRuntime(14997): See documentation: https://docs.devtodev.com/integration/integration-of-sdk-v2/sdk-integration/android
E/AndroidRuntime(14997):        at d2.d.<init>(DeviceManager.kt:13)
E/AndroidRuntime(14997):        at z1.a$a.invoke(Core.kt:13)
E/AndroidRuntime(14997):        at h2.e$a.c(QueueManager.kt:1)
E/AndroidRuntime(14997):        at h2.c.run(Unknown Source:2)
E/AndroidRuntime(14997):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(14997):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(14997):        at java.lang.Thread.run(Thread.java:1012)
```

All libs are added to build.gradle, triple checked your docs but found nothing that can help to figure out what's wrong. Also, it's working properly in debug mode. We have no proguard in our setup.

List of libs added as dependencies: 
```
implementation 'com.devtodev:android-analytics:2.3.4'
implementation 'com.android.installreferrer:installreferrer:2.2'
implementation 'com.google.code.gson:gson:2.10.1'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1'
implementation 'com.google.android.gms:play-services-base:18.2.0'
implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
implementation 'com.devtodev:android-google:1.0.0'
```

**Comment by orbit1987** [comment]
If you have a problem with the release build, then most likely you have not added in proguard next options:
-keep class com.devtodev.** { *; }
-dontwarn com.devtodev.**
// For Google Mobile Services 
-keep class com.google.android.gms.** { *; }
// For Huawei Mobile Services 
-keep class com.huawei.hms.**{*;}

Please check these options in your gradle file .

See https://docs.devtodev.com/integration/integration-of-sdk-v2/sdk-integration/android#sdk-obfuscation-rules

**Comment by orbit1987** [comment]
Obfuscation is a mandatory part of the correct work of our SDK.
DTDAnalytics.coppaControlEnable() excludes work with advertising identifiers.
If you use COPA mode then you lose the ability to identify the user as the same after reinstall the application. In addition, the ability to bind user data with data from attribution trackers is lost.

**Comment by nechtas** [comment]
So you mean without Proguard it wouldn't work or what?

**Comment by griever-gf** [comment]
I have the same error (in Unity).
Adding strings to "proguard-user.txt" doesn't help in any way.
Calling coppaControlEnable helps. Well, I added implementation 'com.android.installreferrer:installreferrer:2.2' to mainTemplate.gradle also.
But there is another way to fix this - adding DTDGoogle.unitypackage. In this case there is no need to call coppaControlEnable. I don't used Google Ad ID in any way, but adding DTDGoogle package to a project helped me.
I don't sure what caused this, probably some conflict with Facebook SDK. Because in the beginning there was no such a bug, only after switching to Facebook SDK (and changing JDK to old one in Preferences/eternal tool settings).

**Comment by orbit1987** [comment]
@griever-gf 
For unity you should open a Unity issue
https://github.com/devtodev-analytics/Unity-sdk-3.0

**Comment by orbit1987** [comment]
@nechtas 
Without proguard rules it may not work for release build.
The integration process is described here https://docs.devtodev.com/integration/integration-of-sdk-v2/sdk-integration/android

**Comment by nechtas** [comment]
@orbit1987 
What about a case where we don't have produard?

**Comment by orbit1987** [comment]
@griever-gf 
Why don't you use proguard?

**Comment by nechtas** [comment]
@orbit1987 
Because we use flutter)
