### ISSUE TITLE
Duplicate class a.a

### ISSUE THREAD

**Issue by hg-trv** [devtodev-analytics/android-sdk-2.0#2]
Duplicate class a.a found in modules jetified-android-analytics-2.4.0-runtime (com.devtodev:android-analytics:2.4.0) and jetified-yookassa-android-sdk-6.9.2-runtime (ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:6.9.2)

**Comment by AIGRIND-LLC** [comment]
We faced the same issue. 
If we add both libraries in the project:
```
implementation("ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:6.10.0")
implementation("com.devtodev:android-analytics:2.4.0")
```
we get:
```
Duplicate class a found in modules android-analytics-2.4.0-runtime (com.devtodev:android-analytics:2.4.0) and yookassa-android-sdk-6.10.0-runtime (ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:6.10.0)
Duplicate class b found in modules android-analytics-2.4.0-runtime (com.devtodev:android-analytics:2.4.0) and yookassa-android-sdk-6.10.0-runtime (ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:6.10.0)
```

**Comment by orbit1987** [comment]
At the moment, unfortunately, we have duplicate classes. We cannot remove them because data migration from outdated SDK versions (before version 2.0.0) will not work.
If in your projects you did not use outdated SDK versions before 2.0.0, I can send you a build without a.a classes.

**Comment by AIGRIND-LLC** [comment]
@orbit1987 sure, it would be great!

**Comment by AIGRIND-LLC** [comment]
@orbit1987 please send the build to brigs-vessels.0p@icloud.com

**Comment by orbit1987** [comment]
@AIGRIND-LLC  Our support team has sent you the build
